language: android
jdk: oraclejdk8

#following so that the build runs in the standard environment (more memory)
sudo: required

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod +x gradlew

install:
  - echo no | avdmanager create avd -n acib -k \"system-images;android-24;google_apis;armeabi-v7a\" -f --abi \"armeabi-v7a\" --tag \"google_apis\"
  - emulator -avd acib -engine classic -no-window -verbose &
  - adb wait-for-device get-serialno


# Emulator Management: Create, Start and Wait
before_script:
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &
  - sleep 15


android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - sdkmanager
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    - android-24

    # Additional components
    # design library and Play Services
    - extra-google-m2repository
    - extra-android-m2repository

    -sys-img-armeabi-v7a-android-24
